version: '3'
services:
  web:
    build: .
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - .:/workspace
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ec-db-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_ALLOW_EMPTY_PASSWORD: "yes"
      POSTGRES_ROOT_PASSWORD: ${POSTGRES_ROOT_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}

volumes:
  ec-db-volume: